### ISSUE TITLE
Meet weight load error!

### ISSUE THREAD

**Issue by silence401** [Tangshitao/MVDiffusion#12]
Hi~. When I use depth_gen.ckpt, this error appears, How to solve it?
![image](https://github.com/Tangshitao/MVDiffusion/assets/29566012/7c1362a2-1ce5-41ba-8bcc-1ebfcdd86a1a)

**Comment by Tangshitao** [comment]
It's caused by diffuser version mismatch. You can either use the suggested diffuser version or change 'strict=True to 'strict=False' in https://github.com/Tangshitao/MVDiffusion/blob/2bac595d78c1fc8ecec0be4bc02aadef9df02ed5/test.py#L65
