### ISSUE TITLE
Link for depth weights 

### ISSUE THREAD

**Issue by efyphil** [Tangshitao/MVDiffusion#15]
[Depth-conditioned generation model](https://www.dropbox.com/scl/fi/56hcmoj0tx7lza7s2m0jq/depth_gen.ckpt?rlkey=upcdbd4kxd9zwms78dssm3gh7&dl=0)
[Depth pretrained model](https://www.dropbox.com/scl/fi/56hcmoj0tx7lza7s2m0jq/depth_gen.ckpt?rlkey=upcdbd4kxd9zwms78dssm3gh7&dl=0)
Hello, thanks for works. I don't know either that a mistake or not, but you have same link for depth conditioned and depth pretrained models

**Comment by Tangshitao** [comment]
Sorry about that. It's fixed.

**Comment by efyphil** [comment]
Thanks
