### ISSUE TITLE
MVDiffusion for other stable diffusion models

### ISSUE THREAD

**Issue by JonasSchult** [Tangshitao/MVDiffusion#18]
Hi!

Thanks for your amazing work!

I am wondering whether you plan to release MVDiffusion checkpoints for other stable diffusion models?
Currently, you released SD-2-base for panorama generation.

Do you have any plans to release a checkpoint for `runwayml/stable-diffusion-v1-5` as well?

Best,
Jonas

**Comment by Tangshitao** [comment]
Sorry, we don't have pretrained model for other SD models.

**Comment by JonasSchult** [comment]
Thanks for your reply! :)

**Comment by JonasSchult** [comment]
Retraining with SD v1.5 on my own should be feasable though, isn't it?

**Comment by Tangshitao** [comment]
yes
