### ISSUE TITLE
About the degree of rotation, clockwise or counterclockwise?

### ISSUE THREAD

**Issue by maobenz** [Tangshitao/MVDiffusion#19]
Hello,
Thanks for your excellent work!
I have a question about R and K. When we get R by get_K_R() and I think R is camera to world matrix not world to camera matrix, is it correct? I think the default rotation direction is counterclockwise. However, when i run the demo.py, the results are images by clockwise. Can you tell me the reason?

For example, if I set the degree of rotation to 45,90, then the camera should rotate 45 degrees and 90 degrees counterclockwise around the y-axis, but I see that the two generated images rotate clockwise.

My understanding is that the default direction of the rotation matrix is ​​counterclockwise rotation, which is a positive value.

Thanks a lot!

**Comment by image0202** [comment]
I have the same issue. Have you reached a conclusion?
