### ISSUE TITLE
Does it support image prompt as input?

### ISSUE THREAD

**Issue by asrlhhh** [Tangshitao/MVDiffusion#2]
Apology that I haven't dived into the paper to look for this answer. All the demos and showcases I have seen are based on text prompt. I am wondering if this model supports image prompt as input

**Comment by Tangshitao** [comment]
No, not currently. We will consider this functionality in the future.

**Comment by asrlhhh** [comment]
Thanks for answering!

**Comment by Tangshitao** [comment]
We have support image conditioned generation.

**Comment by asrlhhh** [comment]
Thank you for the update! I will try it out
