### ISSUE TITLE
Question about Multi-view Depth-to-Image Generation Prompt

### ISSUE THREAD

**Issue by wqdong8** [Tangshitao/MVDiffusion#22]
hi, nice work!
I see you mentioned in readme that the prompt for custom data is obtained through blip2, 
Q1: I wonder if all scannet scene prompts are obtained this way when training the Depth-to-Image Generation Network? 

I see you show the generalization capability to out-of-training distribution image on panorama generation demonstrated in supplementary material,
Q2: I wonder if depth guided networks can do out-of-training distribution image generation.

**Comment by Tangshitao** [comment]
Q1: Yes. we use blip2 to process every frame.
Q2: No, we have to finetune single image stable diffusion due to resolution difference (512 vs 256). It cannot do out-of-training distribution image generation.

**Comment by wqdong8** [comment]
Thanks!

**Comment by OrangeSodahub** [comment]
@Tangshitao You use different prompt for every frame when training while use the same prompt when inference? I saw in your paper there is only one prompt of several images.
