### ISSUE TITLE
[Question] 360x180 degree equirectangular stitching 

### ISSUE THREAD

**Issue by phamkhactu** [Tangshitao/MVDiffusion#25]
Hi 

I've seen that model can create panorama. If I have list of images contains almost degree. 
Could I use your model to create 360 image?

Best regrads,
Tu

**Comment by Tangshitao** [comment]
Not sure I understand what you mean. Can you explain you questions in details?

**Comment by phamkhactu** [comment]
yeah,

I want to create 360 image like [that](https://www.360cities.net/). It is a 360 panorama image. it is created from multi sidle image from multi degree. I mean that: "Can your model combine multi image to create 360 panorama ?"

**Comment by Tangshitao** [comment]
Yes, we first generate 8 panoramic images and you can stitch them into a panorama. We release the stitch codes here. https://github.com/Tangshitao/MVDiffusion/blob/main/generate_video_tool/pano_video_generation.py

**Comment by phamkhactu** [comment]
> Yes, we first generate 8 panoramic images and you can stitch them into a panorama. We release the stitch codes here. https://github.com/Tangshitao/MVDiffusion/blob/main/generate_video_tool/pano_video_generation.py

Thanks for your reply.

Could you give me more doc about creating 8 panoramic images? I am a newbie in 360. I've use google street view, it use 42 images with interested point for making it. I have another question:

what is the minimize images need for creating 360 did you use? or Did you use video to making it?

**Comment by Tangshitao** [comment]
The project is for generating panoramic images. I guess what you need is to transform perspective images into panorama images. You can check the repo. https://github.com/timy90022/Perspective-and-Equirectangular
