### ISSUE TITLE
Questions about implementing code for panoramic generation

### ISSUE THREAD

**Issue by 666666yl** [Tangshitao/MVDiffusion#29]
Hello,I am trying to implement your code for Panoramic generation recently, starting by running demo.py. However, I find the generated images are all solid color images. I wonder if I put the pretrained model in the wrong path, especially the files in stable-diffusoin-2-base. Could you please show the path for the files if possible? Thank you.

**Comment by Tangshitao** [comment]
Hi, You need to download the pretrain model here. (https://www.dropbox.com/scl/fi/yx9e0lj4fwtm9xh2wlhhg/pano.ckpt?rlkey=kowqygw7vt64r3maijk8klfl0&dl=0), and put it under weights/model.ckpt
