### ISSUE TITLE
Question about panorama generation at inference

### ISSUE THREAD

**Issue by lukasHoel** [Tangshitao/MVDiffusion#3]
Thanks for sharing this interesting work! :)
After reading about panorama generation in the paper, I have the following question:

How is the correspondence `t^l` between the frames (Fig. 3) obtained at inference/test-time? Is it given as an input in every denoising step? 

Does this mean you do the following things at inference/test-time?

1. Take any existing panorama and project to 8 images
2. Compute correspondences between the 8 images
3. Use the correspondences to generate 8 new images starting from random noise with the generation module

Thank you for clarifying!

**Comment by Tangshitao** [comment]
The correspondences are the same for all the panorama. See the panorama projection matrix here, https://www.cambridgeincolour.com/tutorials/image-projections.htm

**Comment by lukasHoel** [comment]
I see, thanks for the link, now I understand the usage of a fixed homography matrix. May I ask a follow-up question: did you see limitations in fixing the correspondences, e.g. using always 8 frames with the same amount of overlap? Concretely, does it limit the layouts that can be generated in any way? Thanks again :)

**Comment by Tangshitao** [comment]
Can you clarify what layout is? Is it a global structure of room?

**Comment by lukasHoel** [comment]
Yes

**Comment by Tangshitao** [comment]
I didn't see any limitation of global structure. You can try our demo.
