### ISSUE TITLE
Same Question About Panorama Homography Matrix Computation #26

### ISSUE THREAD

**Issue by zhshi0816** [Tangshitao/MVDiffusion#37]
Hi there, 

I just read the closed issue #26. I think there exists a minor issue.It should be ```homo_l = (K_right @ R_right @ torch.inverse(R_left) @ torch.inverse(K_left))``` instead of your current implementation.

For example:
Take a pixel in camera 1: p_1 = (x, y, 1) in homogeneous coordinates
Back project it into a ray in 3D space: P_1 = inv(K_1) * p_1
Decompose the ray in the coordinates of camera 2: P_2 = R_2_1 * P1
Project the ray into a pixel in camera 2: p_2 = K_2 * P_2
Put the equations together: p_2 = [K_2 * R_2_1 * inv(K_1)] * p_1 and R_2_1 should be R_2 * R_1.transposed

Do you agree?

**Comment by Tangshitao** [comment]
The camera metrixes in the codes are world-to-camera. Your implementation is camera-to-world.

**Comment by zhshi0816** [comment]
Oh, I got it. The difference is because of camera-to-world and world-to-camera. That makes sense. But I think my implementation is world-to-camera and yours is camera-to-world. Can you check it again?

**Comment by Tangshitao** [comment]
Yes, you are correct. That's a typo.

**Comment by zhshi0816** [comment]
Thanks!

**Comment by image0202** [comment]
Do you mean that the R obtained from the 'get_K_R' function refers to the camera-to-world transformation?
