### ISSUE TITLE
Question about equation 2

### ISSUE THREAD

**Issue by sangminkim-99** [Tangshitao/MVDiffusion#4]
Hi @Tangshitao,

Thank you for sharing this great work!

While reading the paper, I was confused about some notations.
Specifically, in Equation 2, there are source feature $\bar{F}(s)$ and target feature $\bar{F}^l(t^l_\*)$.
However I'm not certain about the meaning of $\bar{F}(t^l_\*)$.
Is it intended to represent the source feature vector calculated at the target pixel position, or could it be a typo for $\bar{F}^l(t^l_*)$?

Thank you for your attention, and I appreciate your response.

Best regards,
Sang Min Kim

**Comment by Tangshitao** [comment]
It's a typo. It should be \bar{F}^l{t^l_*}

**Comment by sangminkim-99** [comment]
Thank you!

**Comment by Tangshitao** [comment]
Paper fix, close issue
