### ISSUE TITLE
Would you mind to release the training code of the baseline StableDiffusion (panorama/perspective) you trained?

### ISSUE THREAD

**Issue by EchoTHChen** [Tangshitao/MVDiffusion#6]
Hi! This is a great work! I know you will release your code in early August. But I'm still curious about whether it's ok to release the training code of the baseline StableDiffusion (panorama/perspective) you trained. Because I'm beginning to learn Stable Diffusion and wonder more about it in panorama/perspective generation. I would appreciate it if you can also release the code of Stable Diffusion you trained for panorama generation (panorama/perspective).

**Comment by Tangshitao** [comment]
We will release all the codes, both training and testing.

**Comment by EchoTHChen** [comment]
Thanks so much!

**Comment by Tangshitao** [comment]
We have released all codes.

**Comment by EchoTHChen** [comment]
thanks!



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 11, 2023 10:41 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Tangshitao/MVDiffusion] Would you mind to release the trainingcode of the baseline StableDiffusion (panorama/perspective) you trained?(Issue #6)




 
We have released all codes.
